framework:
  router:
    # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
    # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
    default_uri: '%env(DEFAULT_URI)%'

when@prod:
  framework:
    router:
      # defaults to true (throws exception), null (no checking) is preferred in production
      strict_requirements: null
